### ISSUE TITLE
trackRect is empty > (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

### ISSUE THREAD

**Issue by nothing2say-dev** [FredOleary/VideoBiometricsIOS#1]
Hello. I have an issue after tried your solution.

There is always an error from OpenCVImageProcessor.m at the function processImage: 

**libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.5.1) /…/opencv/modules/core/src/matrix_expressions.cpp:24: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

terminating with uncaught exception of type cv::Exception: OpenCV(4.5.1) /…/opencv/modules/core/src/matrix_expressions.cpp:24: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'**

The problem is trackRect is always empty that is why it causes the error. I don't know is there any missing piece?
I did only one change which is trackRect, I have to define it Rect2i instead of Rect2d because OpenCV forces to change it. And I'm not familiar with Objective-C and OpenCV that much. Would you please re-check it? Did I miss something or how to fix it? 

 I am using Xcode 12.4 and OpenCV 4.5.1 (latest release). 

Thank you very much for your solution. 

Best regards,
Nothing2saY

**Comment by nothing2say-dev** [comment]
Hi, I found the solution now. :)
Just changed tractRect to Rect and fixed something a little bit. The rest is great!

**Comment by FredOleary** [comment]
Hi, I’m glad you were able to find a work around for your issue. Certainly processing should not proceed with an empty tracking rectangle. 

One other thing to note is that, as you have probably noticed, there are two methods for tracking heart rate, the FFT and the peak detector. The FFT simply doesn’t have sufficient resolution at low frequencies so I’d tend to rely on the peak detector. (I’m not sure if I ever documented this)

Out of curiosity, how did you find the project and what are you using it for?

 

 

 

From: Nothing2saY ***@***.***>
Reply-To: FredOleary/VideoBiometricsIOS ***@***.***>
Date: Tuesday, March 23, 2021 at 4:52 AM
To: FredOleary/VideoBiometricsIOS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [FredOleary/VideoBiometricsIOS] trackRect is empty > (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist' (#1)

 

Hi, I found the solution now. :)
Just changed tractRect to Rect and fixed something a little bit. The rest is great!
